## Dockerized CentOS 7 image
# use the centos base image provided by dotCloud
FROM centos
MAINTAINER Mike Brigham brigham@adobe.com

# Currently hardcoded to use Java 8-121-13
# ENV JAVA_VERSION_MAJOR=8 \
#    JAVA_VERSION_MINOR=121 \
#    JAVA_VERSION_BUILD=13 \
#    JAVA_URL_HASH=e9e7ea248e2c4826b92b3f075a80e441 

# Update & install Java 8
RUN yum update -y && \
yum install -y wget && \
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
"http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.rpm" && \
yum -y localinstall jre-8u131-linux-x64.rpm && \
rm -f jre-8u131-linux-x64.rpm && \
yum clean all

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
	
